# NumPy

## O que é o NumPy?

O **NumPy** é uma das bibliotecas mais importantes do ecossistema Python para computação numérica.  
Seu principal recurso é o **array multidimensional**, uma estrutura de dados otimizada para armazenar valores do mesmo tipo e realizar operações matemáticas com alto desempenho.

## Por que usar NumPy?

Em comparação com estruturas nativas do Python, o NumPy oferece:

- melhor desempenho em operações numéricas;
- menor consumo de memória em muitos cenários;
- sintaxe mais simples para cálculos em lote;
- base para outras bibliotecas, como Pandas, SciPy, scikit-learn e muitas ferramentas de IA.

> Observação: para executar este notebook, basta ter o pacote `numpy` instalado.

In [ ]:
import numpy as np

print("Versão do NumPy:", np.__version__)

Versão do NumPy: 2.0.2


# 1. Arrays NumPy versus listas Python

Uma **lista Python** é bastante flexível: pode conter tipos diferentes, crescer dinamicamente e ser usada em muitos contextos gerais de programação.

Já um **array NumPy** foi projetado para **cálculos numéricos**.  
Ele normalmente trabalha com dados **homogêneos**, isto é, elementos de um mesmo tipo, o que favorece desempenho e padronização.

## Quando usar lista?

Use lista quando:

- os dados forem variados;
- você precisar de muita flexibilidade estrutural;
- o foco não for computação numérica.

## Quando usar array NumPy?

Use array NumPy quando:

- os dados forem numéricos;
- você precisar fazer contas com muitos valores;
- quiser trabalhar com vetores, matrizes e estatística;
- precisar de melhor performance.

## Ideia principal

Pense assim:

- **lista Python** → estrutura geral;
- **array NumPy** → estrutura especializada para matemática e análise numérica.

In [ ]:
# Exemplo com lista Python
lista_notas = [7.5,8.0,9.2,6.8]
print("Lista Python", lista_notas)
print("Tipo: ", type(lista_notas))


Lista Python [7.5, 8.0, 9.2, 6.8]
Tipo:  <class 'list'>


In [ ]:
# Exemplo com array NumPy
array_np = np.array([7.5,8.0,9.2,6.8])
print("Array Numpy", array_np)
print("Tipo: ",type(array_np))

Array Numpy [7.5 8.  9.2 6.8]
Tipo:  <class 'numpy.ndarray'>


In [ ]:
# Comparação simples de comportamento
lista_a = [1,2,3]
lista_b = [4,5,6]

print("Concatenando: ", lista_a + lista_b)

array_a = np.array([1,2,3])
array_b = np.array([4,5,6])

print("Soma: ", array_a + array_b)

Concatenando:  [1, 2, 3, 4, 5, 6]
Soma:  [5 7 9]


## Exercício 1 — comparação entre lista e array

Crie uma lista Python chamada `temperaturas_lista` com os valores `28, 30, 27, 31, 29`.  
Depois:

1. converta essa lista para um array NumPy chamado `temperaturas_array`;
2. exiba os dois tipos com `type()`;
3. some `2` a cada elemento do array NumPy;
4. explique, pela observação do resultado, por que arrays são mais convenientes para operações numéricas em lote.

In [ ]:
temperaturas_lista = [28,30,27,31,29]

array_temp = np.array([28,30,27,31,29])
print(array_temp)
print(type(array_temp))

print(type(temperaturas_lista))
print("Soma de 2 a cada elemento: ",array_temp + 2)
print(" Arrays são mais fáceis de trabalhar pois dá para acessar cada elemento pelo índice e mais fácil visualização")
#No array a operação foi aplicada automaticamente a todos os elementos, sem precisar de loop

[28 30 27 31 29]
<class 'numpy.ndarray'>
<class 'list'>
Soma de 2 a cada elemento:  [30 32 29 33 31]
 Arrays são mais fáceis de trabalhar pois dá para acessar cada elemento pelo índice e mais fácil visualização


## Exercício 2 — análise de comportamento estrutural

Uma escola registrou a quantidade de alunos em cinco turmas: `32, 28, 35, 30, 31`.

Faça o seguinte:

1. armazene os dados em duas estruturas: uma lista Python e um array NumPy;
2. concatene a lista com ela mesma usando o operador `+`;
3. multiplique o array por `2`;
4. compare os resultados e escreva, em comentário, a diferença conceitual entre **concatenar dados** e **duplicar valores**.

In [ ]:
lista = [32,28,35,30,31]
array_np = np.array([32,28,35,30,31])
print("Concatenação: ", lista + lista)
print("Multiplicação: ", array_np * 2)
#A lista comum no Python ao ser multiplicada por 2, apenas a duplica em sequência, enquanto no array a multiplicação por 2 multiplica cada elemento desse array por 2

Concatenação:  [32, 28, 35, 30, 31, 32, 28, 35, 30, 31]
Multiplicação:  [64 56 70 60 62]


# 2. Tipos de dados, acesso a elementos e slicing

## Tipos de dados no NumPy

Os arrays NumPy possuem um atributo importante chamado `dtype`, que indica o tipo de dado armazenado.  
Esse controle é relevante porque influencia:

- uso de memória;
- precisão dos cálculos;
- compatibilidade com outras operações.

Exemplos comuns de tipos:

- `int64` → inteiros;
- `float64` → números decimais;
- `bool` → valores lógicos;
- `str_` ou tipos textuais em alguns contextos.

## Acesso por índice

Assim como nas listas Python, o índice começa em `0`.

Exemplo:

- índice `0` → primeiro elemento;
- índice `1` → segundo elemento;
- índice `-1` → último elemento.

## Slicing

O **slicing** permite extrair partes de um array usando a sintaxe:

```python
array[inicio:fim:passo]
```

Onde:

- `inicio` é o índice inicial;
- `fim` é o índice final (não incluído);
- `passo` é o intervalo entre os elementos.

Essa técnica é muito útil para selecionar subconjuntos de dados.

In [ ]:
idades = np.array([14,15,16,17,18])
print("Array: ", idades)
print("dTypes: ", idades.dtype)

Array:  [14 15 16 17 18]
dTypes:  int64


In [ ]:
pesos = np.array([5.5,3,5], dtype=str)
print("dTypes: ", pesos.dtype)
print(pesos)

dTypes:  <U3
['5.5' '3' '5']


In [ ]:
valores = np.array([10,20,30,40,50,60])
print("Primeiro elemento: ", valores[0])
print("Segundo elemento: ", valores[1])
print("Terceiro elemento: ", valores[2])
print("Último elemento: ", valores[-1])
print("Do índice 1 ao 3: ", valores[1:4])
print("De 2 em 2: ", valores[::2])
print("Invertido: ", valores[::-1])

Primeiro elemento:  10
Segundo elemento:  20
Terceiro elemento:  30
Último elemento:  60
Do índice 1 ao 3:  [20 30 40]
De 2 em 2:  [10 30 50]
Invertido:  [60 50 40 30 20 10]


## Exercício 1 — acesso e recorte de dados

Considere o array com as notas de um aluno em oito atividades:

`[6.5, 7.0, 8.2, 9.0, 5.8, 7.7, 8.5, 6.9]`

Resolva:

1. crie o array com `dtype=float`;
2. mostre a primeira nota, a quarta nota e a última nota;
3. mostre apenas as quatro primeiras notas;
4. mostre apenas as notas em posições pares do array;
5. mostre o array em ordem inversa.

In [ ]:
array = np.array([6.5, 7.0, 8.2, 9.0, 5.8, 7.7, 8.5, 6.9], dtype=float)
print("Primeira nota: ", array[0])
print("Quarta nota: ", array[3])
print("Última nota: ", array[-1])
print("Quatro primeiras notas: ", array[0:4])
print("Notas em posições pares do array: ",array[0::2])
print("Array em ordem inversa: ", array[::-1])

Primeira nota:  6.5
Quarta nota:  9.0
Última nota:  6.9
Quatro primeiras notas:  [6.5 7.  8.2 9. ]
Notas em posições pares do array:  [6.5 8.2 5.8 8.5]
Array em ordem inversa:  [6.9 8.5 7.7 5.8 9.  8.2 7.  6.5]


## Exercício 2 — inspeção de tipo e seleção de intervalo

Uma loja registrou a quantidade de vendas em 7 dias:

`[12, 15, 9, 20, 18, 14, 11]`

Faça o que se pede:

1. crie o array e mostre seu `dtype`;
2. exiba os valores do 2º ao 5º dia;
3. exiba somente os três últimos valores;
4. converta o array para `float`;
5. mostre o novo `dtype` após a conversão.

In [ ]:
vendas = np.array([12, 15, 9, 20, 18, 14, 11])
print(vendas.dtype)
print(vendas[1:5])
print(vendas[-3:])

vendas_float = np.array(vendas, dtype = float)
print(vendas_float.dtype)

int64
[15  9 20 18]
[18 14 11]
float64


# 3. Operações aritméticas vetorizadas e desempenho

Uma das maiores vantagens do NumPy é a **vetorização**.  
Isso significa que podemos aplicar operações a todos os elementos de um array de forma direta, sem escrever laços manualmente em muitos casos.

## Operações comuns

Com arrays NumPy, podemos fazer:

- soma: `a + b`
- subtração: `a - b`
- multiplicação: `a * b`
- divisão: `a / b`
- potência: `a ** 2`

Também podemos combinar arrays com números escalares.

## Vantagem prática

Em vez de percorrer elemento por elemento com `for`, o NumPy realiza operações em bloco.  
Isso deixa o código:

- mais curto;
- mais legível;
- geralmente mais rápido.

## Sobre desempenho

Em tarefas numéricas maiores, arrays NumPy tendem a ser mais eficientes que listas Python, principalmente quando há muitos cálculos repetitivos.

In [ ]:
lista_grande = list(range(1000000))

In [ ]:
%timeit lista_grande_quadrado = [x ** 2 for x in lista_grande]

89.2 ms ± 21.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
import numpy as np

In [ ]:
lista_grande_np = np.array(range(1000000))

In [ ]:
%timeit lista_grande_np_quadrado = lista_grande_np ** 2

1.22 ms ± 111 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
valores = np.array([2,4,6,8])
print("Soma: ",valores + 5)
print("Multiplicação: ", valores * 5)
print("Quadrado: ", valores ** 2)
print("Divisão: ", valores/2)

Soma:  [ 7  9 11 13]
Multiplicação:  [10 20 30 40]
Quadrado:  [ 4 16 36 64]
Divisão:  [1. 2. 3. 4.]


## Exercício 1 — reajuste e desconto em lote

Uma papelaria registrou os preços de 6 produtos:

`[12.0, 25.5, 8.9, 14.2, 30.0, 18.5]`

Faça o seguinte com NumPy:

1. crie um array com esses preços;
2. gere um novo array com aumento de 10%;
3. gere outro array com desconto fixo de `2.0` reais;
4. gere um array com os preços ao quadrado apenas para demonstrar a operação de potência;
5. mostre todos os resultados.

In [ ]:
precos = np.array([12.0, 25.5, 9.8, 14.2, 30.0, 18.5])
print("Aumento: ", precos + 0.10 * precos)
print("Desconto ", precos - 2.0)
print("Preços ao quadrado: ", precos ** 2)

Aumento:  [13.2  28.05 10.78 15.62 33.   20.35]
Desconto  [10.  23.5  7.8 12.2 28.  16.5]
Preços ao quadrado:  [144.   650.25  96.04 201.64 900.   342.25]


## Exercício 2 — total por aluno em duas avaliações

Uma turma realizou duas provas. As notas foram registradas assim:

- Prova 1: `[6.0, 7.5, 8.0, 5.5, 9.0]`
- Prova 2: `[7.0, 6.5, 8.5, 6.0, 8.0]`

Resolva:

1. crie dois arrays, um para cada prova;
2. calcule a soma das notas por aluno;
3. calcule a média final considerando as duas provas;
4. crie um array booleano indicando quais alunos ficaram com média maior ou igual a `7.0`.

In [ ]:
prova1 = np.array([6.0, 7.5, 8.0, 5.5, 9.0])
prova2 = np.array([7.0, 6.5, 8.5, 6.0, 8.0])

soma_prova = prova1 + prova2
media_final = soma_prova/2
aprovado = media_final >= 7.0
print("Soma: ", soma_prova)
print("Média: ",media_final )
print("média igual ou maior que 7.0: ", aprovado )

Soma:  [13.  14.  16.5 11.5 17. ]
Média:  [6.5  7.   8.25 5.75 8.5 ]
média igual ou maior que 7.0:  [False  True  True False  True]


# 4. Arrays multidimensionais e matrizes

Até aqui trabalhamos bastante com arrays unidimensionais.  
Agora vamos avançar para arrays com **mais de uma dimensão**.

## Array unidimensional

Representa uma sequência simples de valores, como um vetor:

```python
[10, 20, 30]
```

## Array bidimensional

Representa uma estrutura em linhas e colunas, como uma tabela ou matriz:

```python
[
  [1, 2, 3],
  [4, 5, 6]
]
```

## Conceitos importantes

- `ndim` → número de dimensões;
- `shape` → formato do array (linhas, colunas, etc.);
- `size` → quantidade total de elementos.

## Acesso em matriz

Em um array bidimensional, acessamos assim:

```python
matriz[linha, coluna]
```

Isso é extremamente útil para planilhas, imagens, tabelas e conjuntos de dados estruturados.

In [ ]:
vetor = np.array([10, 20, 30, 40])


In [ ]:
matriz = np.array([
    [10, 20, 30, 40],
    [1, 2, 3, 4],
    [7, 8, 9, 10]
])

In [ ]:
print(matriz[0,0])
print(matriz[1,1])
print(matriz[1,3])
print(matriz[1,0])

print(matriz.ndim)
print(matriz.shape)
print(matriz.size)

10
2
4
1
2
(3, 4)
12


In [ ]:
print("Linha 0, coluna 2: ", matriz[0,2])
print("Segunda linha: ", matriz[1])
print("Terceira coluna: ", matriz[:,2])
print("Submatriz 2x2: ", matriz[:2, :2])


Linha 0, coluna 2:  30
Segunda linha:  [1 2 3 4]
Terceira coluna:  [30  3  9]
Submatriz 2x2:  [[10 20]
 [ 1  2]]


## Exercício 1 — análise de uma tabela de notas

Uma professora organizou as notas de 3 alunos em 4 atividades na forma de uma matriz:

```python
[
    [7.0, 8.5, 6.0, 9.0],
    [5.5, 7.0, 8.0, 6.5],
    [9.0, 8.5, 9.5, 10.0]
]
```

Faça o seguinte:

1. crie a matriz NumPy;
2. mostre sua quantidade de dimensões;
3. mostre seu formato com `shape`;
4. exiba a nota do aluno da segunda linha na terceira coluna;
5. exiba todas as notas do terceiro aluno;
6. exiba todas as notas da segunda atividade.

In [ ]:
notas = np.array([
    [7.0, 8.5, 6.0, 9.0],
    [5.5, 7.0, 8.0, 6.5],
    [9.0, 8.5, 9.5, 10.0]
])
print(notas.ndim)
print(notas.shape)
print(notas[1,2])
print(notas[2])
print(notas[:,1])

2
(3, 4)
8.0
[ 9.   8.5  9.5 10. ]
[8.5 7.  8.5]


## Exercício 2 — extração de subconjunto em matriz

Uma escola registrou a quantidade de livros lidos por 4 turmas ao longo de 3 meses:

```python
[
    [12, 15, 18],
    [10, 14, 16],
    [8, 11, 13],
    [20, 22, 25]
]
```

Resolva:

1. crie a matriz;
2. exiba a linha referente à 4ª turma;
3. exiba a coluna referente ao 2º mês;
4. exiba a submatriz contendo apenas as duas primeiras turmas e os dois primeiros meses;
5. informe o total de elementos da matriz.

In [ ]:
livros = np.array(
    [
    [12, 15, 18],
    [10, 14, 16],
    [8, 11, 13],
    [20, 22, 25]
]
)

print(livros[3])
print(livros[:,1])
print(livros[:2,:2])
print(livros.size)

[20 22 25]
[15 14 11 22]
[[12 15]
 [10 14]]
12


# 5. Estatística com NumPy

O NumPy possui várias funções estatísticas prontas, muito úteis para análise de dados.

## Máximo e mínimo

- `np.max(array)` → maior valor
- `np.min(array)` → menor valor

## Média

- `np.mean(array)` → média aritmética

## Mediana

- `np.median(array)` → valor central dos dados ordenados

## Amplitude

A amplitude pode ser calculada como:

```python
np.max(array) - np.min(array)
```

Ela mostra a diferença entre o maior e o menor valor.

## Percentis e quartis

- `np.percentile(array, 25)` → 1º quartil
- `np.percentile(array, 50)` → mediana
- `np.percentile(array, 75)` → 3º quartil

## Desvio padrão

- `np.std(array)` → mede a dispersão dos dados em relação à média

Quanto maior o desvio padrão, mais espalhados os dados tendem a estar.

In [ ]:
dados = np.aray([10,20,30,40,50])
print("Máximo: ", np.max(dados))
print("Minimo: ", np.min(dados))

## Exercício 1 — resumo estatístico de rendimento

Uma empresa registrou a quantidade de atendimentos concluídos por dia em uma semana:

`[18, 22, 19, 25, 30, 24, 20]`

Faça o seguinte:

1. crie o array;
2. calcule o valor máximo e o mínimo;
3. calcule a média;
4. calcule a mediana;
5. calcule a amplitude;
6. calcule o desvio padrão.

In [ ]:
atend = np.array([18, 22, 19, 25, 30, 24, 20])
print("Máximo: ", np.max(atend))
print("Minimo: ", np.min(atend))
print("Média: ", np.mean(atend))
print("Mediana: ", np.median(atend))
print("Amplitude: ", np.max(atend) - np.min(atend))
print("Desvio padrão: ", np.std(atend))

Máximo:  30
Minimo:  18
Média:  22.571428571428573
Mediana:  22.0
Amplitude:  12
Desvio padrão:  3.8491981672307083


## Exercício 2 — percentis e interpretação de distribuição

Um professor organizou as notas finais de 10 estudantes:

`[4.5, 5.0, 6.0, 6.5, 7.0, 7.2, 7.8, 8.0, 8.5, 9.5]`

Resolva:

1. calcule a média;
2. calcule a mediana;
3. encontre o percentil 25 e o percentil 75;
4. calcule o valor máximo e o mínimo;
5. calcule a amplitude;
6. escreva, em comentário, o que os quartis ajudam a entender sobre a distribuição dos dados.

In [ ]:
import numpy as np

In [ ]:
notas = np.array([4.5,5.0,6.0,6.5,7.0,7.2,7.8,8.0,8.5,9.5])
print("Média: ", np.mean(notas))
print("Mediana: ", np.median(notas))
print("Q1: ", np.percentile(notas,25))
print("Q3: ", np.percentile(notas,75))
print("Max: ", np.max(notas))
print("Min: ", np.min(notas))
print("Amplitude: ",np.max(notas) - np.min(notas))

#Os quartis ajudam a entender como os dados estão distribuídos
#

Média:  7.0
Mediana:  7.1
Q1:  6.125
Q3:  7.95
Max:  9.5
Min:  4.5
Amplitude:  5.0


# 6. Métodos importantes do NumPy

Agora vamos estudar quatro funções muito usadas na criação de arrays:

- `np.arange()`
- `np.linspace()`
- `np.random.randint()`
- `np.random.rand()`

Essas funções ajudam a gerar dados rapidamente para testes, simulações, gráficos e exercícios.

## 6.1 `np.arange()`

A função `np.arange()` cria uma sequência numérica com início, fim e passo.

### Sintaxe geral

```python
np.arange(inicio, fim, passo)
```

- o valor `fim` **não é incluído**;
- o passo pode ser positivo ou negativo.

Ela é muito útil quando precisamos gerar intervalos regulares.

In [ ]:
print(np.arange(1,101,1))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


### Exercício 1 — sequência regular para etiquetas

Crie um array com os números de identificação de 100 a 120, pulando de 2 em 2.  
Depois exiba:

1. o array completo;
2. a quantidade de elementos;
3. o último valor gerado.

In [ ]:
array = np.arange(100,121,2)
print(array)
print(array.size)
print(array[-1])

[100 102 104 106 108 110 112 114 116 118 120]
11
120


### Exercício 2 — contagem regressiva controlada

Crie uma sequência que vá de `30` até `0`, reduzindo de `3` em `3`.  
Depois:

1. exiba o array;
2. mostre os cinco primeiros elementos;
3. mostre os valores em ordem inversa usando slicing.

In [ ]:
contar = np.arange(30,-1,-3)
print("Array: ", contar)
print("5 primeiros: ", contar[:5])
print("inverso: ", contar[::-1])

Array:  [30 27 24 21 18 15 12  9  6  3  0]
5 primeiros:  [30 27 24 21 18]
inverso:  [ 0  3  6  9 12 15 18 21 24 27 30]


## 6.2 `np.linspace()`

A função `np.linspace()` gera uma quantidade definida de valores igualmente espaçados entre dois extremos.

### Sintaxe geral

```python
np.linspace(inicio, fim, quantidade)
```

Diferente de `arange()`, aqui você define **quantos valores quer**, e não o passo diretamente.

In [ ]:
print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### Exercício 1 — divisão uniforme de intervalo

Gere 9 valores igualmente espaçados entre `0` e `40`.  
Depois:

1. exiba o array;
2. mostre a diferença entre dois valores consecutivos;
3. informe o valor central do array.

In [ ]:
intervalo = np.linspace(0, 40, 9)
print("Array: ", intervalo)
print("Diferença: ", intervalo[1] - intervalo[0])
print("Central: ", intervalo[len(intervalo)//2].round(2))

Array:  [ 0.  5. 10. 15. 20. 25. 30. 35. 40.]
Diferença:  5.0
Central:  20.0


### Exercício 2 — planejamento de metas graduais

Uma equipe definiu uma meta de crescimento gradual de `50` até `80`, distribuída em 7 etapas igualmente espaçadas.

1. gere o array com `linspace`;
2. exiba os valores com duas casas decimais;
3. calcule a média dos valores gerados.

In [ ]:
metas = np.linspace(50.132,80.743,7)
print("Array: ", metas)
print("Arredondar: ", np.round(metas, 2))
print("Média: ", np.mean(metas))

Array:  [50.132      55.23383333 60.33566667 65.4375     70.53933333 75.64116667
 80.743     ]
Arredondar:  [50.13 55.23 60.34 65.44 70.54 75.64 80.74]
Média:  65.43749999999999


## 6.3 `np.random.randint()`

A função `np.random.randint()` gera números inteiros aleatórios em um intervalo.

### Exemplo de uso

```python
np.random.randint(inicio, fim, quantidade)
```

- `inicio` é o menor valor possível;
- `fim` não é incluído;
- `quantidade` define quantos números serão gerados.

Para reprodutibilidade em exercícios, podemos usar `np.random.seed()`.

In [ ]:
array = np.random.randint(100, 501, 180)
print(array)

[288 120 202 221 314 430 187 472 199 459 251 230 249 408 357 443 393 485
 291 376 260 413 121 352 335 444 148 158 269 287 370 289 274 150 463 154
 343 419 230 406 234 120 428 266 373 487 188 415 113 341 364 445 152 485
 439 191 466 363 134 305 180 149 459 487 101 489 153 205 359 409 290 317
 143 261 301 369 450 403 370 314 351 289 395 312 307 336 437 466 152 379
 316 351 287 479 140 256 114 400 164 444 426 108 443 228 235 162 238 180
 491 262 388 478 360 330 140 127 234 300 427 367 132 147 161 315 392 198
 271 459 313 134 326 200 230 356 104 317 354 497 458 382 492 306 114 445
 141 479 278 162 451 330 340 151 195 487 321 330 336 242 270 128 135 112
 259 426 286 342 185 383 165 269 144 161 233 383 127 207 143 439 385 430]


In [ ]:
np.random.seed(42)
print(np.random.randint(1, 61, 6))

[39 52 29 15 43  8]


### Exercício 1 — simulação de sorteio de senhas

Use uma semente aleatória com `np.random.seed(10)` e gere 12 números inteiros aleatórios entre `100` e `200`.

Depois:

1. exiba os valores;
2. informe o maior e o menor;
3. calcule a média dos números sorteados.

In [ ]:
np.random.seed(10)
array = np.random.randint(100,200,12)
print(array)
print(np.max(array))
print(np.min(array))
print(array.mean())
# print("Media: ", np.mean(array).round(2))

[109 115 164 128 189 193 129 108 173 100 140 136]
193
100
140.33333333333334


### Exercício 2 — geração de amostra inteira controlada

Use `np.random.seed(7)` para gerar 15 inteiros aleatórios entre `1` e `7`.

Depois:

1. exiba a amostra;
2. conte quantos valores são maiores que `4`;
3. mostre apenas os valores maiores que `4`.

In [ ]:
np.random.seed(7)
amostra = np.random.randint(1,8,15)
print(amostra)
maior_que_4 = amostra > 4
print(np.sum(maior_que_4)) # 1 é true e 0 é false
print("Valores: ", amostra[maior_que_4])

[5 2 7 4 4 5 2 7 1 2 7 3 3 1 7]
6
Valores:  [5 7 5 7 7 7]


## 6.4 `np.random.rand()`

A função `np.random.rand()` gera números aleatórios no intervalo de `0` até `1`.

Esses valores são do tipo float e costumam ser úteis em:

- simulações;
- testes;
- geração de dados artificiais;
- experimentos estatísticos.

In [ ]:
print(np.random.rand(100))

[0.98863433 0.81874499 0.63650234 0.76108474 0.18802993 0.30765459
 0.24639364 0.59604912 0.09190485 0.89560999 0.46227594 0.44481236
 0.1047113  0.68490404 0.81689399 0.62955017 0.24202261 0.78542072
 0.14567943 0.82727633 0.58070537 0.28937281 0.5132434  0.6288514
 0.2585895  0.84690656 0.42125371 0.89233746 0.83546856 0.09934751
 0.64625411 0.31049457 0.7540532  0.54263166 0.45759887 0.89536678
 0.05725356 0.55731763 0.3279111  0.03527334 0.75351852 0.56174066
 0.89414534 0.59826123 0.33703428 0.98521966 0.11571405 0.05260174
 0.73262191 0.3708749  0.36146508 0.87653216 0.32729365 0.8889886
 0.64398798 0.32904954 0.05953265 0.24510935 0.9684132  0.40526764
 0.16003346 0.29801325 0.89957578 0.16497672 0.77786007 0.13486463
 0.96139371 0.53020539 0.04316994 0.93095468 0.35822554 0.73142128
 0.52370801 0.0925818  0.10605922 0.14922495 0.16120001 0.05275579
 0.04701317 0.9484283  0.09129179 0.50835168 0.11862982 0.21478785
 0.76307207 0.93813482 0.46971269 0.00564195 0.9992083  0.047773

### Exercício 1 — amostra decimal aleatória

Use `np.random.seed(3)` e gere 8 valores decimais aleatórios com `np.random.rand()`.

Depois:

1. exiba os valores arredondados com 3 casas decimais;
2. calcule a média;
3. identifique quais valores são maiores que `0.5`.

In [ ]:
np.random.seed(3)
array = np.random.rand(8).round(3)
print(array)
print(array.mean().round(3))
maior_que_05 = array > 0.5
print(array[maior_que_05])

[0.551 0.708 0.291 0.511 0.893 0.896 0.126 0.207]
0.523
[0.551 0.708 0.511 0.893 0.896]


### Exercício 2 — matriz aleatória para teste de sensores

Use `np.random.seed(21)` e crie uma matriz `3 x 4` com valores decimais aleatórios entre `0` e `1`.

Depois:

1. exiba a matriz arredondada com 2 casas decimais;
2. calcule a média de todos os elementos;
3. mostre o maior valor da matriz;
4. mostre a primeira linha.

In [ ]:
np.random.seed(21)
matriz = np.random.rand(3,4). round(2)
media = matriz.mean().round(2)
maior_valor = matriz.max()
primeira = matriz[0]

print("Matriz: ", matriz)
print("Media: ", media)
print("Maior valor: ", maior_valor)
print("Primeira linha: " ,primeira)


Matriz:  [[0.05 0.29 0.72 0.02]
 [0.21 0.05 0.3  0.66]
 [0.31 0.58 0.07 0.87]]
Media:  0.34
Maior valor:  0.87
Primeira linha:  [0.05 0.29 0.72 0.02]


# Encerramento

Neste notebook, você estudou os principais fundamentos do NumPy de forma teórica e prática:

- diferenças entre listas e arrays;
- tipos de dados e fatiamento;
- operações vetorizadas;
- arrays multidimensionais;
- estatística com NumPy;
- funções úteis para geração de sequências e números aleatórios.

Uma boa continuação de estudo é praticar com:

- `reshape()`
- `zeros()`, `ones()`
- filtragem booleana
- broadcasting
- agregações por eixo (`axis=0`, `axis=1`)

Quanto mais exercícios você resolver, mais natural ficará o uso do NumPy.